# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate

# ===============================
# LOG
# ===============================
logging.level.org.springframework=INFO