# ===============================
# DATABASE - POSTGRES (DEV)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/comprar_dev
spring.datasource.username=postgres
spring.datasource.password=159357

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# LOG
# ===============================
logging.level.org.springframework=INFO